# Generated by Django 4.2.7 on 2025-09-14 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='کشور')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='شهر')),
                ('success', models.BooleanField(default=True, verbose_name='موفق')),
                ('failure_reason', models.CharField(blank=True, max_length=100, verbose_name='دلیل عدم موفقیت')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='کلید جلسه')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات اضافی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تاریخچه ورود',
                'verbose_name_plural': 'تاریخچه ورودها',
                'db_table': 'accounts_login_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='accounts_lo_user_id_87f1ee_idx'), models.Index(fields=['ip_address', 'timestamp'], name='accounts_lo_ip_addr_f9bfe9_idx'), models.Index(fields=['success', 'timestamp'], name='accounts_lo_success_799f45_idx')],
            },
        ),
    ]
